/**
 * @fileoverview Externs generated by dts2as from NextGenActionScript.com
 * @externs
 * @suppress {duplicate}
 */

/**
 * @constructor
 */
var Backbone = function() {};

/**
 * @constructor
 */
Backbone.Model = function() {};

/**
 * @constructor
 */
Backbone.View = function() {};

Backbone.View.prototype.on = function () {};
Backbone.View.prototype.off = function () {};
Backbone.View.prototype.trigger = function () {};
Backbone.View.prototype.bind = function () {};
Backbone.View.prototype.unbind = function () {};
Backbone.View.prototype.tagName = {};
Backbone.View.prototype.$ = function () {};
Backbone.View.prototype.initialize = function () {};
Backbone.View.prototype.render = function () {};
Backbone.View.prototype.remove = function () {};
Backbone.View.prototype.make = function () {};
Backbone.View.prototype.setElement = function () {};
Backbone.View.prototype.delegateEvents = function () {};
Backbone.View.prototype.undelegateEvents = function () {};
Backbone.View.prototype._configure = function () {};
Backbone.View.prototype._ensureElement = function () {};
