/**
 * @fileoverview Externs generated by dts2as from NextGenActionScript.com
 * @externs
 * @suppress {duplicate}
 */

/**
 * @constructor
 */
var _ = function() {};

_.prototype.VERSION = function() {};
_.prototype.forEach = function() {};
_.prototype.each = function() {};
_.prototype.collect = function() {};
_.prototype.map = function() {};
_.prototype.inject = function() {};
_.prototype.foldl = function() {};
_.prototype.reduce = function() {};
_.prototype.foldr = function() {};
_.prototype.reduceRight = function() {};
_.prototype.detect = function() {};
_.prototype.find = function() {};
_.prototype.select = function() {};
_.prototype.filter = function() {};
_.prototype.reject = function() {};
_.prototype.all = function() {};
_.prototype.every = function() {};
_.prototype.any = function() {};
_.prototype.some = function() {};
_.prototype.contains = function() {};
_.prototype.include = function() {};
_.prototype.invoke = function() {};
_.prototype.pluck = function() {};
_.prototype.max = function() {};
_.prototype.min = function() {};
_.prototype.shuffle = function() {};
_.prototype.sortBy = function() {};
_.prototype.groupBy = function() {};
_.prototype.sortedIndex = function() {};
_.prototype.toArray = function() {};
_.prototype.size = function() {};
_.prototype.head = function() {};
_.prototype.first = function() {};
_.prototype.initial = function() {};
_.prototype.last = function() {};
_.prototype.tail = function() {};
_.prototype.rest = function() {};
_.prototype.compact = function() {};
_.prototype.flatten = function() {};
_.prototype.without = function() {};
_.prototype.unique = function() {};
_.prototype.uniq = function() {};
_.prototype.union = function() {};
_.prototype.intersect = function() {};
_.prototype.intersection = function() {};
_.prototype.difference = function() {};
_.prototype.zip = function() {};
_.prototype.indexOf = function() {};
_.prototype.lastIndexOf = function() {};
_.prototype.range = function() {};
_.prototype.bind = function() {};
_.prototype.bindAll = function() {};
_.prototype.memoize = function() {};
_.prototype.delay = function() {};
_.prototype.defer = function() {};
_.prototype.throttle = function() {};
_.prototype.debounce = function() {};
_.prototype.once = function() {};
_.prototype.wrap = function() {};
_.prototype.compose = function() {};
_.prototype.after = function() {};
_.prototype.keys = function() {};
_.prototype.values = function() {};
_.prototype.methods = function() {};
_.prototype.functions = function() {};
_.prototype.extend = function() {};
_.prototype.defaults = function() {};
_.prototype.clone = function() {};
_.prototype.tap = function() {};
_.prototype.isEqual = function() {};
_.prototype.isEmpty = function() {};
_.prototype.isElement = function() {};
_.prototype.isArray = function() {};
_.prototype.isObject = function() {};
_.prototype.isArguments = function() {};
_.prototype.isFunction = function() {};
_.prototype.isString = function() {};
_.prototype.isNumber = function() {};
_.prototype.isNaN = function() {};
_.prototype.isBoolean = function() {};
_.prototype.isDate = function() {};
_.prototype.isRegExp = function() {};
_.prototype.isNull = function() {};
_.prototype.isUndefined = function() {};
_.prototype.has = function() {};
_.prototype.noConflict = function() {};
_.prototype.identity = function() {};
_.prototype.times = function() {};
_.prototype.escape = function() {};
_.prototype.mixin = function() {};
_.prototype.uniqueId = function() {};
_.prototype.template = function() {};
_.prototype.chain = function() {};